name: Go Test Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '^1.23'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./... -v
